1- Array Creation Functions

In [1]:
import numpy as np

In [2]:
#creating array from list

In [3]:
a=[1,2,3]

In [4]:
arr = np.array(a)

In [5]:
arr

array([1, 2, 3])

In [6]:
type(a)

list

In [7]:
type(arr)

numpy.ndarray

In [8]:
#creating an array with evenly spaced values

In [9]:
b = np.arange(0,10,2) #values from 0 to 10 with step 2
b

array([0, 2, 4, 6, 8])

In [10]:
f1 = np.arange(50,100,5)

In [11]:
f1

array([50, 55, 60, 65, 70, 75, 80, 85, 90, 95])

In [12]:
#Create an array with evenly spaced values
c = np.linspace(2,10,5)

In [13]:
c

array([ 2.,  4.,  6.,  8., 10.])

In [14]:
c = np.linspace(0,10,3)

In [15]:
c

array([ 0.,  5., 10.])

In [16]:
# creating an array filled with zeros
z1 = np.zeros((8,3)) #default it will print float values

In [17]:
z1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
z2 = np.zeros((9,10),dtype=int) #hyperparameter tunning 
z2

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [19]:
o1 = np.ones((5,15)) #By default it will print float values 

In [20]:
o1

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [21]:
o2 = np.ones((10,10),dtype=int) #hyperparameter tunning as the values are changed to integer from float
o2

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [22]:
#create an identity matrix
i1 = np.eye(2) #2*2 identity matrix 
i1

array([[1., 0.],
       [0., 1.]])

In [23]:
i2 = np.eye(5)
i2

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
i3 = np.eye(3)
i3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
i4 = np.eye(4)
print('Array i4 =\n',i4)

Array i4 =
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


2-Array Manipulation Function

In [26]:
#Reshape an array

In [27]:
c1 = np.array([1,2,3])
r1 = np.reshape(c1,(1,3))
r1

array([[1, 2, 3]])

In [28]:
r2 = np.reshape(c1,(3,1))
r2

array([[1],
       [2],
       [3]])

In [29]:
v1 =np.array([0,1,2,3,4,5,6,7,8,9])
r3 = np.reshape(v1,(5,2))
r3

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [30]:
r4 = np.reshape(v1,(2,5))
r4

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [31]:
#flatten an array

In [32]:
a5 = np.array([[1,2,3],[4,5,6]])
a5

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
a6 = np.array([1,2,3])
a6

array([1, 2, 3])

In [34]:
a7 = np.array([[1,2,3],[4,5,6],[7,8,9]])
a7

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
flat_a5 = np.ravel(a5)
flat_a5

array([1, 2, 3, 4, 5, 6])

In [36]:
flat_a6 = np.ravel(a6)
flat_a6

array([1, 2, 3])

In [37]:
flat_a7 = np.ravel(a7)
flat_a7

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
#Transpose an array
#In transpose () rows will convert in columns
ar1 = np.array([[1,2],[3,4]])
trans_ar1 = np.transpose(ar1)
print(ar1)
print(trans_ar1)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [39]:
ar2 = np.array([[1,2,3],[4,5,6]])
trans_ar2 = np.transpose(ar2)
print(ar2)
print(trans_ar2)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [40]:
ar3 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
trans_ar3 = np.transpose(ar3)
print(ar3)
print(trans_ar3)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [41]:
#stack arrays vertically
a_1 = np.array([1,2])
a_2 = np.array([3,4])
a_12 = np.vstack([a_1,a_2])
print(a_12)

[[1 2]
 [3 4]]


In [42]:
b_1 = np.array([[1,2],[3,4]])
b_2 = np.array([5,6])
b_12 =np.vstack([b_1,b_2])
b_12

array([[1, 2],
       [3, 4],
       [5, 6]])

In [43]:
b_13 = np.hstack(b_1)
b_13

array([1, 2, 3, 4])

3-Mathematical Functions

In [44]:
#Addition inn array
ab1 = np.array([1,2,3])
added = np.add(ab1,2)
added

array([3, 4, 5])

In [45]:
ab2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
add2 = np.add(ab2,4)
add2

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [46]:
#square each element
sq_ab2 = np.power(ab2,2)
sq_ab2

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [47]:
pr_ab2 = np.power(ab2,5)
pr_ab2

array([[     1,     32,    243,   1024],
       [  3125,   7776,  16807,  32768],
       [ 59049, 100000, 161051, 248832]])

In [48]:
sr_ab2 = np.sqrt(ab2)
sr_ab2

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479, 3.46410162]])

In [49]:
sq_3 = np.array([[4,9,16],[25,36,49]])
sqrt_sq3 = np.sqrt(sq_3)

In [50]:
sqrt_sq3

array([[2., 3., 4.],
       [5., 6., 7.]])

In [51]:
print(sq_3)
print(sqrt_sq3)

[[ 4  9 16]
 [25 36 49]]
[[2. 3. 4.]
 [5. 6. 7.]]


In [52]:
print(ab1)
print(sq_3)

[1 2 3]
[[ 4  9 16]
 [25 36 49]]


In [53]:
#dot_p = np.dot(ab1,sq_3)

In [54]:
abc = np.array([4,5,6])

In [55]:
dot_p = np.dot(ab1,abc)
print(dot_p)

32


4-Statistical functions

In [56]:
s = np.array([4,5,6,7])
mean = np.mean(s)

In [57]:
print(mean)

5.5


In [58]:
#standard deviation of an array
std_dev = np.std(s)
print(std_dev)

1.118033988749895


In [59]:
#minimum element of an array
print(np.min(s))

4


In [60]:
#maximum element of an array
max1 = np.max(s)
print(max1)

7


5-Linear Algebra Function

In [65]:
#create a matrix
matrix = np.array([[1,2],[3,4]])
matrix

array([[1, 2],
       [3, 4]])

In [67]:
#Determinant of matrix
determinant = np.linalg.det(matrix)
determinant

np.float64(-2.0000000000000004)

In [69]:
#inverse of a matrix
inverse = np.linalg.inv(matrix)
inverse

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [70]:
print(matrix)
print(determinant)
print(inverse)

[[1 2]
 [3 4]]
-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]


In [71]:
matrix1 = np.array([[2,4],[6,8]])
print(matrix1)
determinant1 = np.linalg.det(matrix1)
print(determinant1)
inverse1 = np.linalg.inv(matrix1)
print(inverse1)

[[2 4]
 [6 8]]
-8.000000000000002
[[-1.    0.5 ]
 [ 0.75 -0.25]]


6-Random sampling functions

In [72]:
#Generate random  values between 0 and 1
random_vals = np.random.rand(3)
random_vals

array([0.63087666, 0.24220944, 0.64037545])

In [114]:
#set seed for reproductivity
np.random.seed(0)

#Generate random values between 0 and 1
random_vals = np.random.rand(3) #Array of 3 random values between 0 and 1
random_vals

array([0.5488135 , 0.71518937, 0.60276338])

In [115]:
#generates random integers
rand_int = np.random.randint(0,10)
rand_int

3

In [116]:
rand_int1 = np.random.randint(10,50,5)
rand_int1

array([49, 19, 29, 31, 46], dtype=int32)

In [117]:
rand_int2 = np.random.randint(10,50,size = 5)
rand_int2

array([33, 16, 34, 34, 22], dtype=int32)

In [118]:
print(rand_int2)

[33 16 34 34 22]


In [119]:
np.random.seed(0)
rand_int3 = np.random.randint(10,50,5)
rand_int3

array([10, 13, 13, 49, 19], dtype=int32)

In [120]:
print(rand_int3)

[10 13 13 49 19]


In [121]:
rand_int3

array([10, 13, 13, 49, 19], dtype=int32)

7-Boolen & Logical functions

In [124]:
#check if all elements are True
logical1 = np.array([True,False,True])
logical_t = np.all(logical1)
print(logical_t)

False


In [126]:
logical2 = np.array([True,True,True])
logical_t2 = np.all(logical2)
print(logical_t2)

True


In [127]:
logical3 = np.array([True,False,False])
logical_t3 = np.any(logical3)
print(logical_t3)

True


In [128]:
logical4 = np.array([False,False])
logical_t4 = np.any(logical4)
print(logical_t4)

False


8-Set operation

In [129]:
# Intersection of two array
set_a = np.array([1,2,3,4])
set_b = np.array([3,4,5,6])
Intersect = np.intersect1d(set_a,set_b)
print(Intersect)

[3 4]


In [130]:
set_x = np.array([[1,2,3],[4,5,6]])
set_y = np.array([[4,5,6],[7,8,9]])
inter1= np.intersect1d(set_x,set_y)
print(inter1)

[4 5 6]


In [131]:
print(set_x)

[[1 2 3]
 [4 5 6]]


In [132]:
print(set_y)

[[4 5 6]
 [7 8 9]]


In [133]:
#Union of two array
union = np.union1d(set_x,set_y)
union

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Array Attribute Function

In [136]:
a10 = np.array([1,2,3])
shape = a10.shape
size = a10.size
dimension = a10.ndim
dtype = a10.dtype
print(a10)
print(shape)
print(size)
print(dimension)
print(dtype)

[1 2 3]
(3,)
3
1
int64


In [137]:
#create a copy of an array
c1 = np.array([1,2,3])
copied = np.copy(c1)
copied

array([1, 2, 3])

In [138]:
#size of an array in bytes
c1_size_byte = c1.nbytes
c1_size_byte

24

In [139]:
#checks if two array shared memory
sh1 = np.shares_memory(c1,copied)
sh1

False